### ISSUE TITLE
ERR_UNKNOWN_FILE_EXTENSION

### ISSUE THREAD

**Issue by willzh** [oclif/hello-world-esm#28]
`
$ bin/dev.js hello  

(node:80707) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: oclif-hello-world [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/Downloads/hello-world-esm-main/src/commands/hello/index.ts
module: @oclif/core@2.11.8
task: toCached
plugin: oclif-hello-world
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:80707) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: oclif-hello-world [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/Downloads/hello-world-esm-main/src/commands/hello/world.ts
module: @oclif/core@2.11.8
task: toCached
plugin: oclif-hello-world
See more details with DEBUG=*
Say hello to the world and others

USAGE
  $ oex hello COMMAND
`

oclif-hello-world/0.1.1 darwin-arm64 node-v19.8.1

**Comment by mdonnalley** [comment]
This template is not expected to work until https://github.com/oclif/core/pull/759 is merged
