### ISSUE TITLE
bin/dev is not working

### ISSUE THREAD

**Issue by f3l1x** [oclif/hello-world-esm#8]
Hi ✋  Thank for this example.

I would like to ask how to use `bin/dev.js`. Because it does not work for me.

```
➜ node bin/dev.js hello world
module: @oclif/core@2.11.1
task: toCached
plugin: fake
root: {mypath}/fake
See more details with DEBUG=*
Error: command hello:world not found
AppleRawMaxCapacity
```

or

```
❯ node bin/dev.js
See more details with DEBUG=*
oclif example Hello World CLI

VERSION
  fake/0.0.0 darwin-arm64 node-v20.5.0

USAGE
  $ fake [COMMAND]

TOPICS
  plugins  List installed plugins.

COMMANDS
  help     Display help for fake.
  plugins  List installed plugins.
```

How can I run `bin/dev hello world`? `bin/run hello world` works fine, but it requires `dist` folder ofc.

Thanks.

**Comment by mdonnalley** [comment]
@f3l1x The `bin/dev.js` script executes using `ts-node` which allows it to compile your code at runtime. By running `node bin/dev.js` you're no longer using `ts-node`, which means the code can't run unless it's already been compiled

**Comment by f3l1x** [comment]
Hi @mdonnalley, thank you for your help, now it works like charm(ander).
